FROM node:16

RUN mkdir -p /home/codex/client
WORKDIR /home/codex/client

RUN apt-get update
RUN apt-get install -y libxi-dev libgl-dev

# Install dependencies
COPY package.json /home/codex/client
RUN npm i

COPY . /home/codex/client
EXPOSE 3000
CMD npm start

