version: "3"
services:
    server:
        build: "./server"
        restart: "always"
        networks:
            - "codex"
    frontend-dev:
        build:
            context: "./client"
            dockerfile: "Dockerfile-dev"
        volumes:
            - "./client/src:/home/codex/client/src"
        restart: "always"
        networks:
            - "codex"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=1000
    webserver:
        image: nginx
        ports:
            - "8000:80"
        networks:
            - "codex"
        volumes:
            - "./codex_webserver-dev.conf:/etc/nginx/conf.d/default.conf"
networks:
    codex:
