version: "3"
services:
    backend:
        build: "./server"
        # volumes:
        #     - "./server:/home/codex/server"
        networks:
            - codex
    frontend:
        build:
            context: "./client"
        networks:
            - codex
    webserver:
        build:
            context: "./webserver"
        # ports:
        #     - "3000:3000"
        networks:
            - codex
    webserver_test:
        build:
            context: "./webserver_test"
        ports:
            - "3001:80"
networks:
    codex:
