version: "3"
services:
    codex:
        build: "./"
        ports:
            - "3000:3000"
            - "3001:3001"
            - "8888:8888"
            - "42354:42354"
        restart: "always"
