version: "3"
services:
    server:
        build: "./server"
        restart: "always"
        networks:
            - "codex"
    frontend:
        build: "./client"
        restart: "always"
        platform: "linux/x86_64"
        networks:
            - "codex"
        environment:
            - CODEX_SERVER_URL
    webserver:
        image: nginx
        ports:
            - "8000:80"
        networks:
            - "codex"
        volumes:
            - "./codex_webserver.conf:/etc/nginx/conf.d/default.conf"

networks:
    codex:
