version: "3"
services:
    backend:
        build: "./server"
        # volumes:
        #     - "./server:/home/codex/server"
        ports:
            - "8888:8888"
    frontend:
        build:
            context: "./client"
        ports:
            - "3000:3000"
        environment:
            - CODEX_SERVER_URL
