export const NO_ACTION = "NO_ACTION";
export const FILE_LOAD = "FILE_LOAD";
export const FEATURE_ADD = "FEATURE_ADD";
export const FEATURE_SELECT = "FEATURE_SELECT";
export const FEATURE_UNSELECT = "FEATURE_UNSELECT";
export const FEATURES_UNSELECTALL = "FEATURES_UNSELECTALL";
export const CREATE_FEATURE_GROUP = "CREATE_FEATURE_GROUP";
export const CHANGE_FEATURE_GROUP = "CHANGE_FEATURE_GROUP";
export const SELECT_FEATURE_GROUP = "SELECT_FEATURE_GROUP";
export const DELETE_FEATURE_GROUP = "DELETE_FEATURE_GROUP";
export const RENAME_FEATURE_GROUP = "RENAME_FEATURE_GROUP";

// feature lifetime reference counting
export const FEATURE_LIFETIME_RETAIN = "FEATURE_LIFETIME_RETAIN";
export const FEATURE_LIFETIME_RELEASE = "FEATURE_LIFETIME_RELEASE";

export const FEATURE_LIST_LOADING = "FEATURE_LIST_LOADING";

export const SELECTION_REORDER = "SELECTION_REORDER";
export const SELECTION_RECOLOR = "SELECTION_RECOLOR";
export const SELECTION_RENAME = "SELECTION_RENAME";
export const SET_SELECTION_GROUP = "SET_SELECTION_GROUP";
export const SELECTION_EMPHASIZE = "SELECTION_EMPHASIZE";
export const SELECTION_TOGGLE = "SELECTION_TOGGLE";
export const SELECTIONS_UNSELECTALL = "SELECTIONS_UNSELECTALL";
export const SELECTION_REMOVE = "SELECTION_REMOVE";
export const REMOVE_ALL_SELECTIONS = "REMOVE_ALL_SELECTIONS";
export const BRUSH_UPDATE = "BRUSH_UPDATE";
export const BRUSH_UPDATE_AREA = "BRUSH_UPDATE_AREA";
export const BRUSH_CLEAR = "BRUSH_CLEAR";
export const UPDATE_DATA = "UPDATE_DATA";
export const ADD_DATASET = "ADD_DATASET";
export const ADD_FEATURE = "ADD_FEATURE";
export const DELETE_FEATURE = "DELETE_FEATURE";
export const RENAME_FEATURE = "RENAME_FEATURE";

export const OPEN_GRAPH = "OPEN_GRAPH";
export const OPEN_ALGORITHM = "OPEN_ALGORITHM";
export const OPEN_REPORT = "OPEN_REPORT";
export const OPEN_DEVELOPMENT = "OPEN_DEVELOPMENT";
export const OPEN_WORKFLOW = "OPEN_WORKFLOW";
export const BRUSHTYPE_SET = "BRUSHTYPE_SET";
export const BRUSHID_SET = "BRUSHID_SET";
export const MODE_SET = "MODE_SET";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";

export const GET_GRAPH_DATA = "GET_GRAPH_DATA";
export const GET_HELP_TEXT = "GET_HELP_TEXT";

export const OPEN_NEW_WINDOW = "OPEN_NEW_WINDOW";
export const CLOSE_WINDOW = "CLOSE_WINDOW";
export const CLOSE_ALL_WINDOWS = "CLOSE_ALL_WINDOWS";
export const TOGGLE_MINIMIZE_WINDOW = "TOGGLE_MINIMIZE_WINDOW";
export const SET_WINDOW_HOVER = "SET_WINDOW_HOVER";
export const UPDATE_WINDOW_INFO = "UPDATE_WINDOW_INFO";

export const GET_ALGORITHM_DATA = "GET_ALGORITHM_DATA";
export const LOADING_ALGORITHM = "LOADING_ALGORITHM";

export const CLOSE_SOCKET = "CLOSE_SOCKET";

export const SET_CURRENT_SELECTION = "SET_CURRENT_SELECTION";
export const SAVE_CURRENT_SELECTION = "SAVE_CURRENT_SELECTION";
export const TOGGLE_SELECTION_ACTIVE = "TOGGLE_SELECTION_ACTIVE";
export const TOGGLE_SELECTION_HIDDEN = "TOGGLE_SELECTION_HIDDEN";
export const SAVE_NEW_SELECTION = "SAVE_NEW_SELECTION";
export const DELETE_SELECTION = "DELETE_SELECTION";
export const RENAME_SELECTION = "RENAME_SELECTION";
export const HOVER_SELECTION = "HOVER_SELECTION";
export const CREATE_SELECTION_GROUP = "CREATE_SELECTION_GROUP";
export const TOGGLE_GROUP_ACTIVE = "TOGGLE_GROUP_ACTIVE";
export const TOGGLE_GROUP_HIDDEN = "TOGGLE_GROUP_HIDDEN";
export const DELETE_SELECTION_GROUP = "DELETE_SELECTION_GROUP";
export const RENAME_SELECTION_GROUP = "RENAME_SELECTION_GROUP";
export const SET_SELECTION_ACTIVE = "SET_SELECTION_ACTIVE";
export const SET_SELECTION_HIDDEN = "SET_SELECTION_HIDDEN";
export const SET_GROUP_HIDDEN = "SET_GROUP_HIDDEN";
export const SET_GROUP_ACTIVE = "SET_GROUP_ACTIVE";

export const SIMPLE_REQUEST = "SIMPLE_REQUEST";

export const STAT_SET_FEATURE_LOADING = "STAT_SET_FEATURE_LOADING";
export const STAT_SET_FEATURE_RESOLVED = "STAT_SET_FEATURE_RESOLVED";
export const STAT_SET_FEATURE_FAILED = "STAT_SET_FEATURE_FAILED";

// Window Manager Actions
export const SET_WINDOW_TILE_ACTION_PENDING = "SET_WINDOW_TILE_ACTION_PENDING";
export const UPDATE_WINDOWS = "UPDATE_WINDOWS";
export const WINDOW_SET_TITLE = "WINDOW_SET_TITLE";
export const WINDOW_RESIZE = "WINDOW_RESIZE";
export const WINDOW_SET_RESIZABLE = "WINDOW_SET_RESIZABLE";
export const WINDOW_MOVE = "WINDOW_MOVE";
export const WINDOW_SET_DATA = "WINDOW_SET_DATA";
export const WINDOW_SET_ACTIVE = "WINDOW_SET_ACTIVE";
export const WINDOW_SET_TYPE = "WINDOW_SET_TYPE";

export const CHANGE_GLOBAL_CHART_STATE = "CHANGE_GLOBAL_CHART_STATE";

// UI features
export const SET_UPLOAD_STATE_UPLOADING = "SET_UPLOAD_STATE_UPLOADING";
export const SET_UPLOAD_STATE_PROCESSING = "SET_UPLOAD_STATE_PROCESSING";
export const SET_UPLOAD_STATE_DONE = "SET_UPLOAD_STATE_DONE";
export const SHOW_CONFIRMATION_MODAL = "SHOW_CONFIRMATION_MODAL";
export const HIDE_CONFIRMATION_MODAL = "HIDE_CONFIRMATION_MODAL";
export const CLOSE_GRAPH_WHEN_DELETE_FEATURE = "CLOSE_GRAPH_WHEN_DELETE_FEATURE";
export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const SET_STATS_PANEL_HIDDEN = "SET_STATS_PANEL_HIDDEN";

// Graph actions
export const SET_WINDOW_FEATURES = "SET_WINDOW_FEATURES";
export const WINDOW_SET_NEEDS_AUTOSCALE = "WINDOW_SET_NEEDS_AUTOSCALE";
