export const NO_ACTION = "NO_ACTION";
export const FILE_LOAD = "FILE_LOAD";
export const FEATURE_ADD = "FEATURE_ADD";
export const FEATURE_SELECT = "FEATURE_SELECT";
export const FEATURE_UNSELECT = "FEATURE_UNSELECT";
export const FEATURES_UNSELECTALL = "FEATURES_UNSELECTALL";

export const FEATURE_LIST_LOADING = "FEATURE_LIST_LOADING";

export const SELECTION_REORDER = "SELECTION_REORDER";
export const SELECTION_RECOLOR = "SELECTION_RECOLOR";
export const SELECTION_RENAME = "SELECTION_RENAME";
export const SELECTION_EMPHASIZE = "SELECTION_EMPHASIZE";
export const SELECTION_TOGGLE = "SELECTION_TOGGLE";
export const SELECTIONS_UNSELECTALL = "SELECTIONS_UNSELECTALL";
export const SELECTION_REMOVE = "SELECTION_REMOVE";
export const BRUSH_UPDATE = "BRUSH_UPDATE";
export const BRUSH_UPDATE_AREA = "BRUSH_UPDATE_AREA";
export const BRUSH_CLEAR = "BRUSH_CLEAR";
export const UPDATE_DATA = "UPDATE_DATA";

export const OPEN_GRAPH = "OPEN_GRAPH";
export const OPEN_ALGORITHM = "OPEN_ALGORITHM";
export const OPEN_REPORT = "OPEN_REPORT";
export const OPEN_DEVELOPMENT = "OPEN_DEVELOPMENT";
export const BRUSHTYPE_SET = "BRUSHTYPE_SET";
export const BRUSHID_SET = "BRUSHID_SET";
export const MODE_SET = "MODE_SET";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";

export const GET_GRAPH_DATA = "GET_GRAPH_DATA";
export const GET_HELP_TEXT = "GET_HELP_TEXT";

export const OPEN_NEW_WINDOW = "OPEN_NEW_WINDOW";
export const CLOSE_WINDOW = "CLOSE_WINDOW";
export const CLOSE_ALL_WINDOWS = "CLOSE_ALL_WINDOWS";
export const TOGGLE_MINIMIZE_WINDOW = "TOGGLE_MINIMIZE_WINDOW";
export const SET_WINDOW_HOVER = "SET_WINDOW_HOVER";
export const UPDATE_WINDOW_INFO = "UPDATE_WINDOW_INFO";

export const GET_ALGORITHM_DATA = "GET_ALGORITHM_DATA";
export const LOADING_ALGORITHM = "LOADING_ALGORITHM";

export const CLOSE_SOCKET = "CLOSE_SOCKET";

export const CREATE_SELECTION = "CREATE_SELECTION";

// Window Manager Actions
export const SET_WINDOW_TILE_ACTION_PENDING = "SET_WINDOW_TILE_ACTION_PENDING";
export const UPDATE_WINDOWS = "UPDATE_WINDOWS";
