export const EXPLAIN_THIS = "Explain This";
export const FILTER = "Filter";
export const FIND_MORE_LIKE_THIS = "Find More Like This";
export const GENERAL_CLASSIFIER = "General Classifier";

export const EXPLAIN_THIS_WINDOW = "EXPLAIN_THIS_WINDOW";
export const FIND_MORE_LIKE_THIS_WINDOW = "FIND_MORE_LIKE_THIS_WINDOW";
export const FILTER_WINDOW = "FILTER_WINDOW";
export const GENERAL_CLASSIFIER_WINDOW = "GENERAL_CLASSIFIER_WINDOW";

export const WORKFLOW_TYPES = [EXPLAIN_THIS, FILTER, FIND_MORE_LIKE_THIS, GENERAL_CLASSIFIER];
