name: codex

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.6
    - coverage
    - h5py
    - scipy
    - pytest
    - pyyaml
    - yaml
    - matplotlib
    - tornado
    - psutil
    - pandas
    - pillow
    - psutil
    - msgpack-python
    - pyzmq
    - termcolor
    - pip
    - numpy
    - scikit-image
    - pip:
          - pysptools
          # - scikit-image==0.15.0
          - fastdtw
          - Pebble
          - pytest-cov==2.7.1
          # - numpy==1.14.3
          - scikit-learn==0.20.3
          - fastapi==0.83.0
