name: codex

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - coverage
  - h5py
  - numpy=1.14.3
  - scipy
  - scikit-learn=0.20.3
  - pytest
  - pyyaml
  - yaml
  - matplotlib
  - tornado=4.5.3
  - psutil
  - pandas
  - pillow
  - psutil
  - certifi=2018.11.29 # required for mlib
  - basemap=1.2.0 #required for mlib
  - jsoncpp # required for mlib
  - pip
  - pip:
    - pysptools
    - scikit-image
    - fastdtw
    - vtk==8.1.2 # required for mlib
    - mlib-python36/
